### ISSUE TITLE
project not running on windows env.

### ISSUE THREAD

**Issue by masoudsalehi** [mxstbr/login-flow#11]
checked out the project ran install command and failed on start command.

**Comment by masoudsalehi** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.3.12
3 info using node@v5.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle reactjs-boilerplate@2.3.0~prestart: reactjs-boilerplate@2.3.0
6 silly lifecycle reactjs-boilerplate@2.3.0~prestart: no script for prestart, continuing
7 info lifecycle reactjs-boilerplate@2.3.0~start: reactjs-boilerplate@2.3.0
8 verbose lifecycle reactjs-boilerplate@2.3.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle reactjs-boilerplate@2.3.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\msalehisedeh\Desktop\IPS\login-flow-master\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Java\jre7\bin;C:\Program Files (x86)\RSA SecurID Token Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft Application Virtualization Client;C:\Program Files (x86)\Shoreline Communications\ShoreWare Client\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\WebEx\PTools020000000;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\msalehisedeh\AppData\Roaming\npm
10 verbose lifecycle reactjs-boilerplate@2.3.0~start: CWD: C:\Users\msalehisedeh\Desktop\IPS\login-flow-master
11 silly lifecycle reactjs-boilerplate@2.3.0~start: Args: [ '/d /s /c', 'NODE_ENV=development node server.js' ]
12 silly lifecycle reactjs-boilerplate@2.3.0~start: Returned: code: 1  signal: null
13 info lifecycle reactjs-boilerplate@2.3.0~start: Failed to exec start script
14 verbose stack Error: reactjs-boilerplate@2.3.0 start: `NODE_ENV=development node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid reactjs-boilerplate@2.3.0
16 verbose cwd C:\Users\msalehisedeh\Desktop\IPS\login-flow-master
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v5.4.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error reactjs-boilerplate@2.3.0 start: `NODE_ENV=development node server.js`
22 error Exit status 1
23 error Failed at the reactjs-boilerplate@2.3.0 start script 'NODE_ENV=development node server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the reactjs-boilerplate package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     NODE_ENV=development node server.js
23 error You can get their info via:
23 error     npm owner ls reactjs-boilerplate
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by mxstbr** [comment]
I'm not personally using Windows, but this should just be a case of adding [cross-env](https://github.com/kentcdodds/cross-env) to the npm command. If you'd like to submit a PR for that, that'd be great!

**Comment by masoudsalehi** [comment]
What is a PR?

Masoud Salehisedeh  |  Fiserv  | Sr UI designer | Innovation & Design (IAD) | Electronic Payments  |  408-664-1084 ext 1084  | 925-984-5368 cell

**Comment by mxstbr** [comment]
Pull Request, on Github

**Comment by beiciye** [comment]
I have also met this issue

**Comment by mxstbr** [comment]
@beiciye would you like to submit a PR to fix this?

**Comment by beiciye** [comment]
@mxstbr   OK , I will try my best
